//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atom.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atom.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string PageEdit_cs {
            get {
                return ResourceManager.GetString("PageEdit_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;%@ Page Language=&quot;C#&quot; AutoEventWireup=&quot;true&quot; Inherits=&quot;{#ClassName#}&quot; MasterPageFile=&quot;~/MasterPages/MasterPage.master&quot; Codebehind=&quot;{#Codebehind#}&quot; %&gt;
        ///
        ///&lt;asp:Content ID=&quot;Content1&quot; ContentPlaceHolderID=&quot;WorkAreaPH&quot; runat=&quot;Server&quot;&gt;
        ///	&lt;%--Карточка--%&gt;    
        ///	&lt;asp:UpdatePanel UpdateMode=&quot;Conditional&quot; ID=&quot;updCard&quot; runat=&quot;server&quot;&gt;
        ///	&lt;ContentTemplate&gt;        
        ///		{#Content#}
        ///	&lt;/ContentTemplate&gt;
        ///	&lt;/asp:UpdatePanel&gt;
        ///&lt;/asp:Content&gt;.
        /// </summary>
        internal static string PageView {
            get {
                return ResourceManager.GetString("PageView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на namespace SAM.Web.Pages.UL.Documents
        ///{
        ///    using System;
        ///    using System.Collections;
        ///    using System.Data;
        ///    using System.Web.UI;
        ///    using System.Web.UI.WebControls;
        ///	using GP.Web.UI.Controls;
        ///    using GP.Web.UI.Controls.Navigation;
        ///    using Resources.UL.Accounting;
        ///    using Resources.UL.Documents;
        ///    using SAM.Controls;
        ///    using SAM.DAL;
        ///    using SAM.SiteStructure;
        ///    using SAM.Web.Core;
        ///    using SAM.Web.ViewBase.Pages.UL;
        ///
        ///    using MenuItem = GP.Web.UI.Controls.Navigation.M [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string PageView_cs {
            get {
                return ResourceManager.GetString("PageView_cs", resourceCulture);
            }
        }
    }
}
