//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atom
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_MenuGroupView
    {
        public int pkid { get; set; }
        public string nam { get; set; }
        public Nullable<int> sorder { get; set; }
        public Nullable<int> idparent { get; set; }
        public Nullable<bool> isnavshow { get; set; }
        public int idmenugroup { get; set; }
        public string gs { get; set; }
    }
}
