//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atom
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_MenuField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ut_MenuField()
        {
            this.ut_MenuField1 = new HashSet<ut_MenuField>();
            this.ut_RoleField = new HashSet<ut_RoleField>();
        }
    
        public int pkid { get; set; }
        public Nullable<int> idpage { get; set; }
        public string nam { get; set; }
        public string fld { get; set; }
        public Nullable<int> idparent { get; set; }
        public string fldbd { get; set; }
        public string tabbd { get; set; }
        public string keyfield { get; set; }
        public Nullable<int> keyfieldvalue { get; set; }
        public Nullable<int> idparenttable { get; set; }
        public Nullable<bool> isconsidered { get; set; }
        public int isNotEdited { get; set; }
        public Nullable<bool> isFakeHistory { get; set; }
        public string FldParentForParams { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_MenuField> ut_MenuField1 { get; set; }
        public virtual ut_MenuField ut_MenuField2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_RoleField> ut_RoleField { get; set; }
    }
}
