//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atom
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_MenuPageView
    {
        public int pkid { get; set; }
        public Nullable<int> idgroup { get; set; }
        public Nullable<int> idparentpage { get; set; }
        public string nam { get; set; }
        public Nullable<int> sorder { get; set; }
        public Nullable<int> idmenupage { get; set; }
        public string gs { get; set; }
    }
}
