//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atom
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_Roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ut_Roles()
        {
            this.ut_RoleField = new HashSet<ut_RoleField>();
        }
    
        public int pkid { get; set; }
        public string nam { get; set; }
        public string groupad { get; set; }
        public string nams { get; set; }
        public Nullable<bool> isregionrequired { get; set; }
        public Nullable<bool> isblockrequired { get; set; }
        public string gs { get; set; }
        public Nullable<bool> demandmanager { get; set; }
        public Nullable<int> range { get; set; }
        public Nullable<bool> Unpublic { get; set; }
        public Nullable<int> type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_RoleField> ut_RoleField { get; set; }
    }
}
