//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atom
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_RolePage
    {
        public int pkid { get; set; }
        public Nullable<int> idrole { get; set; }
        public Nullable<int> idpage { get; set; }
        public Nullable<int> visability { get; set; }
    
        public virtual ut_MenuPageView ut_MenuPageView { get; set; }
        public virtual ut_Roles ut_Roles { get; set; }
    }
}
